import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ToasterProvider } from '@/providers/ToastProvider'
import { ModalProvider } from '@/providers/ModalProvider'
import { ConfettiProvider } from '@/providers/ConfettiProvider'
// import ActiveListProvider from '@/providers/ActiveListProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <ActiveListProvider /> */}
          <ToasterProvider />
          <ModalProvider />
          <ConfettiProvider />
          {children}

        </body>
      </html>
    </ClerkProvider>
  )
}
